Repository TimeYourTask/Tyta-frontend, pull requests merged in 2022-12, with the labels that each got.

#20 bug/TYTA-118/use-navigate-hook-instead-of-link-component-404-back-home-button
  src/pages/Forbidden/Forbidden.jsx
  src/pages/NotFound/NotFound.jsx
Labels: PR - Review OK

#21 task/TYTA-34/login-component
  src/Router.jsx
  src/assets/login.webp
  src/pages/Login/Login.jsx
  src/pages/Login/Login.scss
Labels: PR - Review OK

#22 story/TYTA-47/let-user-reset-his-password
  .env.sample
  docker-compose.yml
  package-lock.json
  package.json
  src/Router.jsx
  src/api/axios.config.js
  src/api/user.api.js
  src/pages/ResetPassword/ResetPassword.jsx
  src/pages/ResetPassword/ResetPassword.scss
Labels: PR - Review TO DO

#24 Pull request from hell, some refacto in all app
  .eslintrc.js
  .gitignore
  .prettierrc
  package.json
  src/Router.jsx
  src/api/user.api.js
  src/components/Elements/Notification.jsx
  src/components/Providers/RequireAuth.jsx
  src/components/Sections/Header/Header.jsx
  src/hooks/useNotifications.js
  src/index.jsx
  src/pages/Home/Home.jsx
  src/pages/Login/Login.jsx
  src/pages/ResetPassword/ResetPassword.jsx
  src/store/actions/auth.js
  src/store/actions/notification.js
  src/store/actions/types.js
  src/store/authSlice.js
  src/store/reducer.js
  src/store/reducers/auth.js
  src/store/reducers/index.js
  src/store/reducers/notification.js
  src/store/services/auth-header.js
  src/store/services/auth.service.js
  src/store/services/axios.config.js
  src/store/store.js
Labels: PR - Review OK, commit-by-commit

#25 story/TYTA-106/link-frontend-with-backend-api-for-register
  src/pages/Register/Register.jsx
Labels: PR - Review TO DO

#26 story/TYTA-128/create-landing-page
  src/App.scss
  src/assets/customer.png
  src/assets/homepage.svg
  src/components/Elements/ButtonLink.jsx
  src/components/Elements/ButtonMailto.jsx
  src/components/Sections/Footer/Footer.jsx
  src/components/Sections/Header/Header.jsx
  src/pages/Forbidden/Forbidden.jsx
  src/pages/Home/Home.jsx
  src/pages/NotFound/NotFound.jsx
  src/themes/light.js
Labels: PR - Review TO DO

#28 Add a view to list all teams and view users in it
  .eslintrc.js
  .gitignore
  src/Router.jsx
  src/components/Layouts/Connected/Connected.layout.jsx
  src/pages/Teams/AddUserToTeam/AddUserToTeam.jsx
  src/pages/Teams/ListTeams/ListTeams.jsx
  src/store/actions/auth.js
  src/store/actions/teams.js
  src/store/actions/types.js
  src/store/actions/users.js
  src/store/reducers/index.js
  src/store/reducers/teams.js
  src/store/reducers/users.js
  src/store/services/auth-header.js
  src/store/services/axios.config.js
  src/store/services/teams.service.js
  src/store/services/users.service.js
  yarn.lock
Labels: PR - Review TO DO

#29 story/TYTA-129/global-overview-page-for-user
  .github/PULL_REQUEST_TEMPLATE/new_feature.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .gitignore
  src/App.scss
  src/Router.jsx
  src/components/Layouts/Connected/Connected.layout.jsx
  src/components/Sections/Toolbar/Toolbar.jsx
  src/pages/Overview/Overview.jsx
  yarn.lock
Labels: PR - Review TO DO

#30 Story/tyta 109/add view for creating team
  src/Router.jsx
  src/pages/Teams/AddTeam/AddTeam.jsx
  src/pages/Teams/ListTeams/ListTeams.jsx
  src/store/actions/teams.js
  src/store/reducers/teams.js
  src/store/services/teams.service.js
Labels: PR - Review OK

#32 Story/tyta 111/edit a team
  src/Router.jsx
  src/pages/Teams/ListTeams/ListTeams.jsx
  src/pages/Teams/UpdateTeam/UpdateTeam.jsx
  src/store/actions/teams.js
  src/store/services/teams.service.js
Labels: PR - Review OK

#31 story/TYTA-114/add-view-for-creating-project
  .eslintrc.js
  src/Router.jsx
  src/assets/project-empty-state.svg
  src/pages/Projects/AddUserToProject/AddUserToProject.jsx
  src/pages/Projects/CreateProject/CreateProject.jsx
  src/pages/Projects/EditProject/EditProject.jsx
  src/pages/Projects/TeamProjects/TeamProjects.jsx
  src/pages/Teams/AddTeam/AddTeam.jsx
  src/pages/Teams/AddUserToTeam/AddUserToTeam.jsx
  src/pages/Teams/ListTeams/ListTeams.jsx
  src/pages/Teams/UpdateTeam/UpdateTeam.jsx
  src/store/services/projects.service.js
  src/store/services/teams.service.js
Labels: PR - Review TO DO

#36 bug/TYTA-133/type-email-not-working
  src/pages/Register/Register.jsx
Labels: PR - Review OK
